# This is a basic workflow to help you get started with Actions
name: Execute Unit Tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run-Tests:
    # The type of runner that the job will run on
    runs-on: Windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: .\Build


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup environment
      - name: Setup
        run: .\setup.ps1
        env:
          NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
          NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

      # Run Unit Tests
      - name: Run Unit Tests
        run: .\RunTests.ps1
        continue-on-error: false  # Fail the workflow if tests fail
